return {
	bot_api_key = '',
	admin = ,
	lang = 'en',
	log_chat = ,
	cli_port = 4568,
	about_text = [[
I am mattata, a multi-purpose Telegram bot.

Send /help to get started.
	]],
	cmd_pat = '/',
	drua_block_on_blacklist = false,
	bing_api_key = '',
	google_api_key = '',
	google_cse_key = '',
	owm_api_key = '',
	lastfm_api_key = '',
	biblia_api_key = '',
	thecatapi_key = '',
	nasa_api_key = '',
	yandex_key = '',
	simsimi_key = '',
	simsimi_trial = true,
	errors = {
		generic = 'Error.',
		connection = 'Connection error.',
		results = 'No results found.',
		argument = 'Invalid argument.',
		syntax = 'Invalid syntax.',
		chatter_connection = 'I don\'t feel like talking right now.',
		chatter_response = 'I don\'t know what to say to that.'
	},
	plugins = {
		'control',
		'administration',
		'blacklist',
		'about',
		'whoami',
		'nick',
		'bandersnatch',
		'autoresponses',
		'wikipedia',
		'remind',
		'ping',
		'calc',
		'urbandictionary',
		'pokemon-go',
		'dice',
		'imdb',
		'patterns',
		'me',
		'shout',
		'slap',
		'time',
		'translate',
		'preview',
		'reddit',
		'channel',
		'pokego-calculator',
		'commit',
		'pun',
		'cats',
		'catfact',
		'currency',
		'pokedex',
		'echo',
		'fortune',
		'isup',
		'chuck',
		'loremipsum',
		'baconipsum',
		'skateipsum',
		'starwars',
		'lua',
		'bigtext',
		'help',
		'autoresponses'
	}
}