return { -- rename this file to configuration.lua for mattata to work
	botToken = '', -- insert the bot API token you received from @BotFather
	owner = nil, -- the numerical ID of the owner, who is presumably you
	language = 'en', -- two digit locale
	wikiLanguage = 'en', -- locale to use for wikipedia.lua, set to 'simple' for results from simple wikipedia
	adminGroup = nil, -- the numerical ID of the chat you wish to log errors/private messages to
	aboutText = 'Hello, my name is mattata. I\'m a multi-purpose Telegram bot you can confidently rely on.\nTo get started, just send /help.\n',
 	commandPrefix = '/', -- the symbol bot commands will be executed with ('/' by default)
	fileDownloadLocation = '/tmp/', -- the location to save all downloaded media to
	processMessageEdits = true, -- change this to false to stop mattata from processing message edits
	announceMigration = true, -- change this to false to stop mattata from announcing chat migration information
	plugins = { -- the plugins which mattata will enable on launch
		'control',
		-- place all new plugins below this line
		'bandersnatch',
		'wikipedia',
		'ping',
		'calc',
		'urbandictionary',
		'dice',
		'imdb',
		'slap',
		'time',
		'translate',
		'preview',
		'reddit',
		'channel',
		'commit',
		'pun',
		'cats',
		'catfact',
		'currency',
		'pokedex',
		'eightball',
		'isup',
		'chuck',
		'id',
		'loremipsum',
		'starwars',
		'lua',
		'9gag',
		'lyrics',
		'fact',
		'minecraft',
		'mcmigrated',
		'mcuuid',
		'mchistory',
		'randomword',
		'yeoldinsult',
		'ispwned',
		'yomama',
		'guidgen',
		'pwgen',
		'canitrust',
		'qotd',
		'apod',
		'hackernews',
		'coinflip',
		'doggo',
		'xkcd',
		'jsondump',
		'giphy',
		'itunes',
		'github',
		'identicon',
		'qrgen',
		'bible',
		'echo',
		'synonym',
		'lastfm',
		'spotify',
		'trump',
		'istuesday',
		'tobase64',
		'tohex',
		'hextorgb',
		'isp',
		'rss',
		'dns',
		'tts',
		'location',
		'exec',
		'shorten',
		'weather',
		'youtube',
		'bing',
		'shout',
		'doge',
		'deadbaby',
		'yify',
		'flickr',
		'twitch',
		'plugins',
		'set',
		'get',
		'youtube-dl',
		'github-feed',
		'nick',
		'shell',
		'insult',
		'news',
		'copypasta',
		'tobin',
		'frombin',
		-- place all new plugins above this line
		'help',
		'faces',
		'sed',
		'messaging'
	},
	inlinePlugins = {
		'id',
		'giphy',
		'apod',
		'lastfm',
		'lyrics',
		'bandersnatch',
		'9gag',
		'translate',
		'inline_messaging',
		'help'
	},
	administrationPlugins = {
		'ban',
		'unban',
		'warn',
		'kick',
		'groups',
		'report',
		'blacklist',
		'link',
		'rules'
	},
	groups = {
		['Memes'] = 'https://telegram.me/joinchat/D9oCfkExFv_O2b2HnppZsQ',
		['Off-Topic Geeks'] = 'https://telegram.me/joinchat/DTcYUD8crPKua-yd0gL3bg',
		['Programming'] = 'https://telegram.me/ProgrammingChat',
		['mattata Development'] = 'https://telegram.me/mattata',
		['Music'] = 'https://telegram.me/MusicChat',
		['Cancer'] = 'https://telegram.me/CancerChat',
		['Rextesters'] = 'https://telegram.me/Rextesters',
		['TV/Films'] = 'https://telegram.me/joinchat/D9oCfkE6o5jW5WZAjg7BLQ',
		['Web Design/Development'] = 'https://telegram.me/joinchat/D9oCfj_GgKRY0cc4IKws3w',
		['Android'] = 'https://telegram.me/joinchat/DTcYUEFZwMkqVYuInGCm3g',
		['Post-Elections Discussion'] = 'https://telegram.me/joinchat/D9oCfkDJS6XhsMBt9RRLYQ',
		['Arch Linux'] = 'https://telegram.me/joinchat/D9oCfj_vyorPUa2npKHazg'
	},
	redis = { -- do NOT edit this, unless you know what you are doing!
		host = '127.0.0.1',
		port = 6379,
		use_socket = false,
		password = 'password',
		database = 2
	},
	keys = {
		cats = '', -- http://thecatapi.com/api-key-registration.html
		translate = '', -- https://tech.yandex.com/keys/get/?service=trnsl
		lyrics = '', -- https://developer.musixmatch.com/admin/applications
		canitrust = '', -- https://www.mywot.com/en/signup
		apod = '', -- https://api.nasa.gov/index.html#apply-for-an-api-key
		bible = '', -- https://api.biblia.com/v1/RegisteredApplications/Create
		synonym = '', -- https://tech.yandex.com/keys/get/?service=dict
		lastfm = '', -- http://www.last.fm/api/account/create
		weather = '', -- https://openweathermap.org/api
		google = '', -- https://console.developers.google.com/apis
		bing = '', -- https://datamarket.azure.com/account/keys
		flickr = '', -- https://www.flickr.com/services/apps/create/noncommercial/?
		github_feed = '',
		news = ''
	},
	apis = {
		cats = 'http://thecatapi.com/api/images/get?format=html&type=jpg',
		calc = 'https://api.mathjs.org/v1/?expr=',
		catfact = 'http://catfacts-api.appspot.com/api/facts',
		chuck = 'http://api.icndb.com/jokes/random',
		currency = 'https://www.google.com/finance/converter',
		fact = 'http://mentalfloss.com/api/1.0/views/amazing_facts.json?limit=5000',
		imdb = 'http://www.omdbapi.com/?t=',
		loremipsum = 'http://loripsum.net/api/1/medium/plaintext',
		starwars = 'http://swapi.co/api/films/',
		guidgen = 'http://www.passwordrandom.com/query?command=guid&format=json&count=1',
		pwgen = 'http://passwordwolf.com/api?length=',
		yomama = 'http://api.yomomma.info/',
		ninegag = 'http://api-9gag.herokuapp.com/',
		lyrics = 'https://api.musixmatch.com/ws/1.1/',
		mcmigrated = 'https://eu.mc-api.net/v3/migrated/',
		randomword = 'http://www.setgetgo.com/randomword/get.php',
		translate = 'https://translate.yandex.net/api/v1.5/tr.json/translate?key=',
		urbandictionary = 'http://api.urbandictionary.com/v0/define?term=',
		yeoldinsult = 'http://quandyfactory.com/insult/json',
		canitrust = 'https://api.mywot.com/0.4/public_link_json2?hosts=',
		mcuuid = 'http://mcapi.ca/uuid/player/',
		mchistory = {
			uuid = 'https://api.mojang.com/users/profiles/minecraft/',
			history = 'https://api.mojang.com/user/profiles/'
		},
		ispwned = 'https://haveibeenpwned.com/api/v2/breachedaccount/',
		qotd = 'http://quotes.rest/qod.json',
		apod = 'https://api.nasa.gov/planetary/apod?api_key=',
		identicon = 'http://identicon.rmhdev.net/',
		qrgen = 'http://chart.apis.google.com/chart?cht=qr&chs=500x500&chl=',
		itunes = 'https://itunes.apple.com/search?term=',
		bible = 'http://api.biblia.com/v1/bible/content/ASV.txt?key=',
		synonym = 'https://dictionary.yandex.net/api/v1/dicservice.json/lookup?key=',
		bing = 'https://api.datamarket.azure.com/Data.ashx/Bing/Search/Web?Query=\'%s\'&$format=json',
		lastfm = 'http://ws.audioscrobbler.com/2.0/?method=user.getrecenttracks&format=json&limit=1&api_key=',
		github = 'https://api.github.com/repos/',
		time = 'http://www.timeapi.org/utc/',
		minecraft = 'http://api.syfaro.net/server/status?ip=',
		giphy = 'https://api.giphy.com/v1/gifs/search?q=',
		hackernews = {
			topstories = 'https://hacker-news.firebaseio.com/v0/topstories.json',
			res = 'https://hacker-news.firebaseio.com/v0/item/%s.json',
			art = 'https://news.ycombinator.com/item?id=%s'
		},
		pokedex = 'http://pokeapi.co/api/v1/pokemon/',
		github = 'https://api.github.com/repos/',
		rms = 'https://rms.sexy/img/',
		spotify = 'https://api.spotify.com/v1',
		shorten = 'http://hec.su/api?url=',
		weather = 'http://api.openweathermap.org/data/2.5/weather?q=',
		bing = 'https://api.datamarket.azure.com/Data.ashx/Bing/Search/Web?Query=\''
	},
	joinChatMessages = {
		'Welcome, NAME!',
		'Hello, NAME!',
		'Enjoy your stay, NAME!',
		'I\'m glad you joined, NAME!',
		'Howdy, NAME!',
		'Hi, NAME!',
		'Bonjour, NAME!'
	},
	leftChatMessages = {
		'RIP NAME.',
		'Rest in peace, NAME!',
		'Boy, I sure hope NAME enjoyed their stay!',
		'Was it something I said, NAME?',
		'But we were just getting to know each other, NAME...',
		'Gosh, NAME - am I really THAT bad?',
		'It\'s your loss, NAME.',
		'Come again soon, NAME!',
		'Bye, NAME!',
		'Goodbye, NAME.',
		'Farewell, NAME.'
	},
	errors = {
		generic = 'I\'m afraid an error has occured!',
		connection = 'I\'m sorry, but there was an error whilst I was processing your request, please try again later.',
		results = 'I\'m sorry, but I couldn\'t find any results for that.',
		argument = 'I\'m sorry, but the arguments you gave were either invalid or non-existent. Please try again',
		syntax = 'Syntax error, please try again.'
	},
	messaging = {
		url = 'https://brawlbot.tk/apis/chatter-bot-api/cleverbot.php?text=',
		connectionError = 'Matt\'s words echoed: There\'s a time and place for everything! But not now.',
		responseError = 'I\'m not sure how to answer that...'
	},
	dice = {
		maximumRange = 200,
		maximumCount = 200,
		minimumRange = 2
	},
	bing = {
		maximumResultsPrivate = 8,
		maximumResultsGroup = 4
	},
	remind = {
		persist = true,
		maximumLength = 1000,
		maximumDuration = 526000,
		maximumGroupReminders = 10,
		maximumPrivateReminders = 50
	},
	eightball = {
		answers = {
			'It is certain.',
			'It has been confirmed.',
			'Without any doubts.',
			'Yes, definitely.',
			'You may rely on it.',
			'As I see it, yes.',
			'Most likely.',
			'Outlook: not so good.',
			'Yes.',
			'Signs point to yes.',
			'The reply is very weak, try again.',
			'Ask again later.',
			'I can not tell you right now.',
			'Cannot predict right now.',
			'Concentrate, and then ask again.',
			'Do not count on it.',
			'My reply is no.',
			'My sources say possibly.',
			'Outlook: very good.',
			'Very doubtful.',
			'Rowan\'s voice echoes: There is a time and place for everything, but not now.'
		},
		yes_no_answers = {
			'Absolutely.',
			'In your dreams.',
			'Yes.',
			'No.',
			'It is likely so.',
			'Never!'
		}
	},
	faces = {
		['shrug'] = '¯\\_(ツ)_/¯',
		['lenny'] = '( ͡° ͜ʖ ͡°)',
		['flip'] = '(╯°□°）╯︵ ┻━┻',
		['look'] = 'ಠ_ಠ',
		['shots'] = 'SHOTS FIRED',
		['facepalm'] = '(－‸ლ)',
		['vibrator'] = 'ヽヽ༼༼ຈຈل͜ل͜ຈຈ༽༽ﾉﾉ TURN OFF THE VIBRATOR ヽヽ༼༼ຈຈل͜ل͜ຈຈ༽༽ﾉﾉ',
		['africa'] = '( ͡° ͜ʖ ͡°) Every 60 seconds in Africa, a minute passes. Together we can stop this. Please spread the word ( ͡° ͜ʖ ͡°)',
		['chocolate'] = '\n╔╦╦\n╠╬╬╬╣\n╠╬╬╬╣OK! WHO ATE MY\n╠╬╬╬╣CHOCOLATE!!\n╚╩╩╩╝',
		['kirby'] = '(つ -‘ _ ‘- )つ',
		['finger'] = '\n⁣               /´¯/)\n             ,/¯  /\n             /   /\n          /´¯/’  ’/´¯¯`·¸\n        /’/  /   /    /¨¯\\\n       (‘(   ´  ´   ¯~/’  ’)\n        \\          ’    /\n        \\   \\       _ ·´\n         \\          (\n          \\          \\,',
		['rub'] = 'ヽ( ° ͜ʖ͡°)ﾉ ʀuʙ ᴍʏ ᴅᴏɴɢᴇʀ ヽ( ° ͜ʖ͡°)ﾉ',
		['flo'] = '<b>:3</b>',
		['eli'] = '<b>xDDD</b>',
		['both'] = '<b>:3 xDDD</b>',
		['hitler'] = '<b>HEIL HITLER?! 卐</b>',
		['party'] = '୧༼ ͡◉ل͜ ͡◉༽୨ (ง ͠° ل͜ °)ง ヽ༼ຈل͜ຈ༽ﾉ ༼ ºل͟º ༽ Join da Party ୧༼ ͡◉ل͜ ͡◉༽୨ (ง ͠° ل͜ °)ง ヽ༼ຈل͜ຈ༽ﾉ ༼ ºل͟º ༽',
		['lift'] = '\n❚█══█❚\nDo you even lift?',
		['specs'] = 'ᒡ◯ᵔ◯ᒢ',
		['sarah'] = '❤️',
		['tobs'] = '<b>TOBS IS A SEXY FUCKER AYYYYY LMAOOOOOOO</b>'
	},
	bandersnatch = {
		fullNames = {
			'Wimbledon Tennismatch',
			'Rinkydink Curdlesnoot',
			'Butawhiteboy Cantbekhan',
			'Benadryl Claritin',
			'Bombadil Rivendell',
			'Wanda Crotchfruit',
			'Biblical Concubine',
			'Syphilis Cankersore',
			'Buckminster Fullerene',
			'Bourgeoisie Capitalist'
		},
		firstNames = {
			'Bumblebee',
			'Bandersnatch',
			'Broccoli',
			'Rinkydink',
			'Bombadil',
			'Boilerdang',
			'Bandicoot',
			'Fragglerock',
			'Muffintop',
			'Congleton',
			'Blubberdick',
			'Buffalo',
			'Benadryl',
			'Butterfree',
			'Burberry',
			'Whippersnatch',
			'Buttermilk',
			'Beezlebub',
			'Budapest',
			'Boilerdang',
			'Blubberwhale',
			'Bumberstump',
			'Bulbasaur',
			'Cogglesnatch',
			'Liverswort',
			'Bodybuild',
			'Johnnycash',
			'Bendydick',
			'Burgerking',
			'Bonaparte',
			'Bunsenburner',
			'Billiardball',
			'Bukkake',
			'Baseballmitt',
			'Blubberbutt',
			'Baseballbat',
			'Rumblesack',
			'Barister',
			'Danglerack',
			'Rinkydink',
			'Bombadil',
			'Honkytonk',
			'Billyray',
			'Bumbleshack',
			'Snorkeldink',
			'Anglerfish',
			'Beetlejuice',
			'Bedlington',
			'Bandicoot',
			'Boobytrap',
			'Blenderdick',
			'Bentobox',
			'Anallube',
			'Pallettown',
			'Wimbledon',
			'Buttercup',
			'Blasphemy',
			'Snorkeldink',
			'Brandenburg',
			'Barbituate',
			'Snozzlebert',
			'Tiddleywomp',
			'Bouillabaisse',
			'Wellington',
			'Benetton',
			'Bendandsnap',
			'Timothy',
			'Brewery',
			'Bentobox',
			'Brandybuck',
			'Benjamin',
			'Buckminster',
			'Bourgeoisie',
			'Bakery',
			'Oscarbait',
			'Buckyball',
			'Bourgeoisie',
			'Burlington',
			'Buckingham',
			'Barnoldswick'
		},
		lastNames = {
			'Coddleswort',
			'Crumplesack',
			'Curdlesnoot',
			'Calldispatch',
			'Humperdinck',
			'Rivendell',
			'Cuttlefish',
			'Lingerie',
			'Vegemite',
			'Ampersand',
			'Cumberbund',
			'Candycrush',
			'Clombyclomp',
			'Cragglethatch',
			'Nottinghill',
			'Cabbagepatch',
			'Camouflage',
			'Creamsicle',
			'Curdlemilk',
			'Upperclass',
			'Frumblesnatch',
			'Crumplehorn',
			'Talisman',
			'Candlestick',
			'Chesterfield',
			'Bumbersplat',
			'Scratchnsniff',
			'Snugglesnatch',
			'Charizard',
			'Carrotstick',
			'Cumbercooch',
			'Crackerjack',
			'Crucifix',
			'Cuckatoo',
			'Cockletit',
			'Collywog',
			'Capncrunch',
			'Covergirl',
			'Cumbersnatch',
			'Countryside',
			'Coggleswort',
			'Splishnsplash',
			'Copperwire',
			'Animorph',
			'Curdledmilk',
			'Cheddarcheese',
			'Cottagecheese',
			'Crumplehorn',
			'Snickersbar',
			'Banglesnatch',
			'Stinkyrash',
			'Cameltoe',
			'Chickenbroth',
			'Concubine',
			'Candygram',
			'Moldyspore',
			'Chuckecheese',
			'Cankersore',
			'Crimpysnitch',
			'Wafflesmack',
			'Chowderpants',
			'Toodlesnoot',
			'Clavichord',
			'Cuckooclock',
			'Oxfordshire',
			'Cumbersome',
			'Chickenstrips',
			'Battleship',
			'Commonwealth',
			'Cunningsnatch',
			'Custardbath',
			'Kryptonite',
			'Curdlesnoot',
			'Cummerbund',
			'Coochyrash',
			'Crackerdong',
			'Curdledong',
			'Crackersprout',
			'Crumplebutt',
			'Colonist',
			'Coochierash',
			'Thundersnatch'
		}
	},
	deadbabyjokes = {
		'*What is funnier than a dead baby?*\nA dead baby in a clown costume.',
		'*What is the difference between a baby and a onion?*\nNo one cries when you chop up the baby.',
		'*What is the difference between a dead baby and a watermelon?*\nOne\'s fun to hit with a sledgehammer, the other one\'s a watermelon.',
		'*What is the difference between a baby and a dart-board?*\nDart-boards don\'t bleed.',
		'*What is the difference between a baby and a Mars bar?*\nAbout 500 calories.',
		'*Why did the family take the dead baby along on the cookout?*\nSo they could light it and toast their marshmallows.',
		'*Why was the dead baby kept in the kitchen drawer?*\nThe family used it to crack nuts.',
		'*Why do people keep dead babies in the recreation room?*\nSo they can cut off one leg and use it as a ping-pong paddle.',
		'*Why do you put babies into blenders feet first?*\nSo you can see the expression on their faces.',
		'*Why do people boil water when a baby is being born?*\nSo that if it\'s born dead they can make soup!',
		'*Why did the baby cross the road?*\nIt was stapled to the chicken, that\'s why!',
		'*How many babies does it take to make a bottle of baby oil?*\nIt depends on how hard you squeeze them.',
		'*How many babies can fit in a blender?*\nIt depends on how powerful the blender is.',
		'*How do you know when a baby is dead?*\nIt doesn\'t cry if you nail its feet to the ceiling.',
		'*How do you find a live baby in a pile of dead ones?*\nJab \'em all with a pitchfork.',
		'*How do you save a drowning baby?*\nHarpoon it.',
		'*How do you turn a baby into a dog?*\nPour gas over it and light a match.\n_Woof._',
		'*How do you turn a baby into a cat?*\nFreeze it solid, then run it through a bandsaw.\n_Meow._',
		'*How do you get 100 babies into a single bucket?*\nWith a blender.\n*How do you get them out again?*\nBy using them as a dip for your Doritos.',
		'*How do you make a dead baby float?*\nTake your foot off of its head.',
		'*How do you make a dead baby float?*\n1 glass of soda water and 2 scoops of baby.',
		'*What do you call two abortions in a bucket?*\nBlood brothers.',
		'*What is red and creeps up your leg?*\nAn abortion with homesickness.',
		'*What is a foot long and can make a woman scream?*\nStillbirth.',
		'*What is a foot long, blue, and makes women scream in the morning?*\nCrib death.',
		'*What do you call a dead baby pinned to your wall?*\nArt.',
		'*What is red, bubbles, and scratches at the window before exploding?*\nA baby in a microwave.',
		'*What is blue, yellow and sits at the bottom of the pool?*\nA baby with punctured floaties.',
		'*What is red, yellow and floats at the top of the pool?*\nFloaties with a punctured baby.',
		'*What is red and hangs around trees?*\nA baby that has been hit by a snow blower.',
		'*What is green and hangs around trees?*\nA baby that has been hit by a snow blower, and found 3 weeks later.',
		'*What is pink, red, silver and crawls into walls?*\nA baby with forks in its eyes.',
		'*What is pink and goes black with a \'hiss\'?*\nA baby being thrown into a furnace.',
		'*What is brown and gurgles?*\nA baby in a casserole.',
		'*What is purple, lavished in blood and squeals?*\nA peeled baby in a bag of salt.',
		'*What is black and goes up and down?*\nA baby in a toaster.',
		'*What is red and hangs out of the back of a train?*\nA miscarriage.',
		'*What is red and goes round and round?*\nA baby in a garbage disposal.',
		'*What is red and swings back and forth?*\nA baby on a meat hook.',
		'*What is red, screams, and goes around in circles?*\nA baby nailed to the floor.',
		'*What is red and sits in the corner?*\nA baby with razor blades.',
		'*What is blue and sits in the corner?*\nA baby in a baggie.',
		'*What is black and sits in a corner?*\nA baby with it\'s finger in a power socket.',
		'*What is green and sits in the corner?*\nA baby with it\'s finger in a power socket, found 2 weeks later.',
		'*What is black and charred?*\nA baby chewing on an extension cord.',
		'*What is black and white, runs around the room, and smokes?*\nA baby with his hair on fire.',
		'*What is blue and flies around the room at high speeds?*\nA baby with a punctured lung.',
		'*What is cold, blue and doesn\'t move?*\nA baby in your freezer.',
		'*What is pink, flies and squeals?*\nA baby fired from a catapult.\n*What do you call the baby when it lands?*\nFree pizza.',
		'*What is red and has more brains than the baby you just shot?*\nThe wall behind it.',
		'*What is white and glows pink?*\nA dead baby with an electrode up its ass.',
		'*What is more fun than nailing a baby to a wall?*\nRipping it off again.',
		'*What is more fun than throwing a baby off the cliff?*\nCatching it with a pitchfork.',
		'*What is more fun than swinging babies around on a clothesline?*\nStopping them with a shovel.',
		'*What is more fun than shoveling dead babies off your porch?*\nDoing it with a snow blower.',
		'*What sits in the kitchen and keeps getting smaller and smaller?*\nA baby combing it\'s hair with a potato peeler.',
		'*What bounces up and down at 100mph?*\nA baby tied to the back of a truck.',
		'*What goes plop, plop, fizz, fizz?*\nTwins in an acid bath.',
		'*What is red and pink and can\'t turn around in a corridor?*\nA baby with a javelin through its throat.',
		'*What is little, but can\'t fit through a door?*\nA baby with a spear in its head.',
		'*What is the definition of fun?*\nPlaying fetch with a pitbull and a baby.',
		'*What has 4 legs and one arm?*\nA doberman on a children\'s playground.',
		'*What has 4 legs, 10 arms and blood all over it?*\nA pitbull in front of a pile of dead babies.',
		'*What is red and pink and hanging out of your dog\'s mouth?*\nYour baby\'s leg, LOL!',
		'*What should you get for a dead baby for its birthday?*\nA dead puppy.',
		'*What is grosser than ten dead babies nailed to a tree?*\nOne dead baby nailed to ten trees.',
		'*What is worse than a dead baby in a trash can?*\n100 dead babies in a trash can.\n*You know what is worse than that?*\nThere\'s a live one at the bottom.\n*You know what is worse than that?*It eats its way out.\n*You know what is even worse than that?*\nIt comes back for seconds.',
		'*You know what\'s gross?*\nRunning over a baby with a truck.\n*You know what\'s worse?*\nSkidding on it.\n*You know what\'s worse than that?*\nPeeling it off of the tires.',
		'*What is the worst part about killing a baby?*\nGetting blood on your clown outfit.'
	},
	trumps = {
		'VICTIM is a clown!',
		'VICTIM is a dummy!',
		'VICTIM is one of the dumbest of all pundits',
		'VICTIM has no sense of the real world!',
		'VICTIM is closing in on being the dumbest of them all',
		'VICTIM doesn\'t have a clue',
		'VICTIM is a disaster',
		'VICTIM is a dope!',
		'VICTIM knows nothing',
		'VICTIM is dumb!',
		'VICTIM is trying to extort $1,000,000.00 from me',
		'VICTIM is so disgraceful!',
		'VICTIM tried to extort $1,000,000 from me',
		'VICTIM is a total loser!',
		'VICTIM tried to shake me down for one million dollars',
		'VICTIM is a great big phony',
		'VICTIM represents conservative values terribly & are bad for America',
		'VICTIM asked me for $1 million. I said no & they went negative. Extortion!',
		'VICTIM went hostile w/ a series of incorrect & ill-informed ads',
		'VICTIM is a total fraud',
		'VICTIM is so unbelieveably crooked',
		'VICTIM is falsely advertising',
		'VICTIM is so little respected',
		'VICTIM is a total hypocrites!',
		'VICTIM is a great big phony',
		'VICTIM is a big fat mistake',
		'VICTIM is a failed \'Bushy\' & PA Governor',
		'VICTIM shouldn\'t be allowed to do bias commentary',
		'VICTIM has a faulty thought process',
		'VICTIM is a failed Jeb Bushy',
		'VICTIM never says anything good & never will',
		'VICTIM shouldn\'t even be on the air!',
		'VICTIM should be fired!',
		'VICTIM is so biased',
		'VICTIM is totally unfair',
		'VICTIM still thinks Romney won',
		'VICTIM is a dummy',
		'VICTIM has no credibility',
		'VICTIM is a loser',
		'VICTIM is pushing Republicans down the same old path of defeat',
		'VICTIM is dopey',
		'VICTIM is an establishment flunky',
		'VICTIM should get a life',
		'VICTIM just totally bombed',
		'VICTIM has ZERO credibility',
		'VICTIM is an establishment dope',
		'VICTIM has made so many mistakes',
		'VICTIM is part of the Republican Establishment problem',
		'VICTIM is an all talk, no action dummy!',
		'VICTIM is a total fool',
		'VICTIM purposely mischaracterised my statement',
		'VICTIM is a big fat moron',
		'VICTIM is a biased dope',
		'VICTIM is easy to beat!',
		'VICTIM spent $430 million and lost ALL races',
		'VICTIM wasted $400 million',
		'VICTIM didn\'t win one race',
		'VICTIM is a total loser',
		'VICTIM is a clown with zero credibility',
		'VICTIM is an irrelevant clown, sweats and shakes nervously',
		'VICTIM has no credibility',
		'VICTIM is a Bush plant who called all races wrong',
		'VICTIM is a dopey political pundit',
		'VICTIM is one of the dumber people on television',
		'VICTIM is a fraud',
		'VICTIM is just pathetic',
		'VICTIM is paid for by the politicians bosses',
		'VICTIM is a total #Mediafraud',
		'VICTIM is a joke!',
		'VICTIM is in pocket of Wall Street',
		'VICTIM is owned by the banks',
		'VICTIM took hundreds of thousands of dollars in gifts',
		'VICTIM is bought and paid for by special interests!',
		'VICTIM is a terrible representative of Evangelicals',
		'VICTIM is a nasty guy with no heart!',
		'VICTIM is a total clown',
		'VICTIM is a low-class slob',
		'VICTIM knows nothing about me or my religion',
		'VICTIM came to my office looking for work',
		'VICTIM is a total disaster for Republicans & America',
		'VICTIM is a total disaster',
		'VICTIM is failing so badly that it will soon be taken off thr air',
		'VICTIM is close to death',
		'VICTIM is a dead T.V.',
		'VICTIM should be put to sleep',
		'VICTIM is a total loser',
		'VICTIM is sloppy',
		'VICTIM is grubby',
		'VICTIM is a total mess-big crime',
		'VICTIM is going through massive attacks to its people by the migrants allowed to enter the country',
		'VICTIM is a total phony and con man',
		'VICTIM is a total phony',
		'VICTIM is just a dishonest guy',
		'VICTIM asked me for expensive hotel rooms',
		'VICTIM is a bad guy!',
		'VICTIM is a total scam on our system and country',
		'VICTIM is a total waste of money',
		'VICTIM has too much staff being paid way too much money',
		'VICTIM is a toy by comparison',
		'VICTIM is a V.P.candidate who failed badly',
		'VICTIM has a dead campaign',
		'VICTIM is terrible at business',
		'VICTIM did such a horrible job',
		'VICTIM is a waste',
		'VICTIM is all talk, no action',
		'VICTIM is a very stupid, highly incompetent person running our country into the ground',
		'VICTIM is just plain incompetent',
		'VICTIM is in total disarray',
		'VICTIM is a dishonest journlist',
		'VICTIM is part of the dishonest media',
		'VICTIM is losing too much money. Great news!',
		'VICTIM is going out of business',
		'VICTIM has no money, no cred!',
		'VICTIM is a  very untalented reporter',
		'VICTIM is considered by many in the world of politics to be the dumbest and most slanted of the political sites',
		'VICTIM is a scam!',
		'VICTIM is dishonest',
		'VICTIM is pure scum',
		'VICTIM is so dishonest!',
		'VICTIM has no power',
		'VICTIM is a clown',
		'VICTIM is a serious hater',
		'VICTIM is really dishonest',
		'VICTIM is losing lots of money',
		'VICTIM is not read or respected by many',
		'VICTIM goes out of their way to distort truth!',
		'VICTIM covers me more inaccurately than any other media source',
		'VICTIM is an incompetent judge!',
		'VICTIM has embarrassed all by making very dumb political statements about me',
		'VICTIM has a mind that is shot',
		'VICTIM should resign!',
		'VICTIM is totally ineffective & has been for years',
		'VICTIM questioned me in such a nasty fashion',
		'VICTIM is bad at math, nobody cares what they say in their editorials anymore, especially me!',
		'VICTIM reported \'Cruz momentum\' but nothing about the fact that I easily won!',
		'VICTIM is so dishonest',
		'VICTIM so totally wrong',
		'VICTIM loves to write badly about me',
		'VICTIM looks like a tabloid',
		'VICTIM is ever-dwindling',
		'VICTIM hAS BAD JUDGEMENT',
		'VICTIM is really dumb',
		'VICTIM should never have been written',
		'VICTIM is back to doing very sleazy and dishonest \'pushpolls\' on me',
		'VICTIM is begging for money like a dog',
		'VICTIM is biased',
		'VICTIM is a @FoxNews flunky',
		'VICTIM is a Iraq war monger',
		'VICTIM is highly overrated',
		'VICTIM should be fired',
		'VICTIM a dope',
		'VICTIM is bought and paid for by lobbyists!',
		'VICTIM will never MAKE AMERICA GREAT AGAIN!',
		'VICTIM has the worst voting record in the U.S. Senate in many years',
		'VICTIM is a total lightweight',
		'VICTIM is scamming Florida',
		'VICTIM is a dishonest lightweight',
		'VICTIM is a fraud lightweight',
		'VICTIM is a big loser',
		'VICTIM puts out ad that my pilot was a drug dealer- not true, not my pilot!',
		'VICTIM has the worst record',
		'VICTIM never even shows up to vote',
		'VICTIM treated America\'s ICE officers \'like absolute trash\' in order to pass Obama\'s amnesty',
		'VICTIM gave amnesty to criminal aliens guilty of \'sex offenses.\' DISGRACE!',
		'VICTIM is just another Washington D.C. politician',
		'VICTIM has poor work ethic!',
		'VICTIM is set to be the \'puppet\' of the special interest Koch brothers',
		'VICTIM is the lightweight no show Senator from Florida',
		'VICTIM is not as smart as Cruz, and may be an even bigger liar',
		'VICTIM doesn\'t even show up for votes!',
		'VICTIM is a choker, and once a choker, always a choker!',
		'VICTIM not presidential material',
		'VICTIM looks like a little boy on stage',
		'VICTIM is very weak on illegal immigration',
		'VICTIM is a lightweight choker',
		'VICTIM couldn\'t even respond properly to President Obama\'s State of the Union Speech without pouring sweat & chugging water',
		'VICTIM is a highly overrated politician',
		'VICTIM cannot be President',
		'VICTIM only won the debate in the minds of desperate people',
		'VICTIM is very disloyal to Jeb',
		'VICTIM is weak on illegal immigration',
		'VICTIM is VERY weak on illegal immigration',
		'VICTIM is perfect little puppet',
		'VICTIM is very disloyal',
		'VICTIM never made ten cents',
		'VICTIM is totally controlled',
		'VICTIM is lazy',
		'VICTIM has worst voting record in Senate',
		'VICTIM is very weak on stopping illegal immigration',
		'VICTIM knows nothing about finance',
		'VICTIM is VERY weak on immigration',
		'VICTIM is incapable of making great trade deals',
		'VICTIM is rarely there to vote on a bill',
		'VICTIM has one of the worst attendance record in Senate',
		'VICTIM will allow anyone into the country',
		'VICTIM truly doesn\'t have a clue!',
		'VICTIM is broken, like so much else in our country',
		'VICTIM came out with another one of their phony polls',
		'VICTIM should be totally discredited',
		'VICTIM cannot report the news truthfully',
		'VICTIM choked like a dog',
		'VICTIM is a mixed up man who doesn\'t have a clue. No wonder he lost!',
		'VICTIM is a total joke, and everyone knows it!',
		'VICTIM is a disaster candidate who had no guts and choked',
		'VICTIM begged me for my endorsement four years ago',
		'VICTIM doesn\'t know how to win',
		'VICTIM didn\'t show his tax return until SEPTEMBER 21, 2012, and then only after being humiliated by Harry R',
		'VICTIM is one of the dumbest and worst candidates in the history of Republican politics',
		'VICTIM is so awkward and goofy',
		'VICTIM blew an election that should have never been lost',
		'VICTIM had a terrible \'choke\' loss to Obama',
		'VICTIM lost an election that should have easily been won',
		'VICTIM should not be allowed on TV',
		'VICTIM is truly one of the dumbest of the talking heads',
		'VICTIM consistently fumbles & misrepresents poll results',
		'VICTIM has been so wrong & hates it!',
		'VICTIM is in a total meltdown',
		'VICTIM has a weakness that is the greatest recruiting tool of ISIS!!!',
		'VICTIM continues to report fictious poll numbers',
		'VICTIM is pushing the GOP around',
		'VICTIM wants ridiculous debate terms',
		'VICTIM is a crime and killing machine',
		'VICTIM is so unbelievably crooked',
		'VICTIM wants to flood our country with Syrian immigrants that we know little or nothing about',
		'VICTIM is a liar!',
		'VICTIM betrayed Bernie voters',
		'VICTIM is not at all loyal',
		'VICTIM killed jobs!',
		'VICTIM is against steelworkers and miners',
		'VICTIM destroyed jobs and manufacturing',
		'VICTIM led Obama into bad decisions!',
		'VICTIM will sell our country down the tubes!',
		'VICTIM is bought and paid for by Wall Street, lobbyists and special interests',
		'VICTIM is a DISASTER on foreign policy',
		'VICTIM is Sad!!',
		'VICTIM is not qualified',
		'VICTIM has WEAK leadership',
		'VICTIM is sooooo guilty',
		'VICTIM lied to the FBI and to the people of our country',
		'VICTIM has very bad judgement',
		'VICTIM is not fit to lead!',
		'VICTIM is unfit to serve as President',
		'VICTIM hAS BAD JUDGEMENT!',
		'VICTIM is a total disgrace!',
		'VICTIM is the founder of ISIS',
		'VICTIM is guilty as hell',
		'VICTIM will NEVER be able to handle the complexities and danger of ISIS',
		'VICTIM is sellng out America',
		'VICTIM has such bad judgement',
		'VICTIM has no sense of markets',
		'VICTIM may be the most corrupt person ever to seek the presidency',
		'VICTIM will be a disaster for jobs and the economy!',
		'VICTIM defrauded America',
		'VICTIM has a judgement that killed thousands, unleashed ISIS and wrecked the economy.',
		'VICTIM has really bad judgement and a temperament',
		'VICTIM is totally unfit to be our president',
		'VICTIM is unable to answer tough questions!',
		'VICTIM has a very bad and destructive track record',
		'VICTIM is not honest!',
		'VICTIM doesn\'t even look presidential!',
		'VICTIM is reading poorly from the telepromter!',
		'VICTIM no longer has credibility',
		'VICTIM has zero natural talent',
		'VICTIM has a very stupid use of e-mails',
		'VICTIM suffers from plain old bad judgement!',
		'VICTIM is reckless and dangerous',
		'VICTIM has zero imagination and even less stamina',
		'VICTIM can\'t close the deal with Bernie Sanders',
		'VICTIM can\'t close the deal on Crazy Bernie',
		'VICTIM has bad judgment!',
		'VICTIM is pushing the false narrative that I want to raise taxes',
		'VICTIM has ZERO leadership ability',
		'VICTIM is constantly playing the women\'s card - it is sad!',
		'VICTIM is dealing with men who get off the reservation.',
		'VICTIM is perhaps the most dishonest person to have ever run for the presidency',
		'VICTIM is one of the all time great enablers!',
		'VICTIM is unqualified to be president',
		'VICTIM has been involved in corruption for most of her professional life!',
		'VICTIM is a major national security risk',
		'VICTIM lied last week',
		'VICTIM doesn\'t have the strength or stamina to be president',
		'VICTIM is a totally flawed candidate',
		'VICTIM lIED at the debate last night',
		'VICTIM does not have the STRENGTH or STAMINA to be President',
		'VICTIM will be soundly defeated',
		'VICTIM won\'t call out radical Islam',
		'VICTIM is afraid of Obama & the emails',
		'VICTIM is totally incompetent as a manager and leader',
		'VICTIM looked lost',
		'VICTIM is 100% CONTROLLED',
		'VICTIM did a terrible job',
		'VICTIM did an absolutely horrible job of securing the border',
		'VICTIM should be ashamed',
		'VICTIM failed on the border',
		'VICTIM should be forced to take an IQ test',
		'VICTIM doesn\'t understand what the word demagoguery means',
		'VICTIM failed at the border',
		'VICTIM needs a new pair of glasses',
		'VICTIM just wants to shut down and go home to bed!',
		'VICTIM totally sold out',
		'VICTIM has done such a complete fold',
		'VICTIM has totally given up on his fight for the people',
		'VICTIM has lost his energy and his strength',
		'VICTIM flamed out',
		'VICTIM has no energy left!',
		'VICTIM is exhausted',
		'VICTIM just can\'t go on any longer',
		'VICTIM is ending really weak',
		'VICTIM has abandoned his supporters',
		'VICTIM is selling out!',
		'VICTIM is lying when he says his disruptors aren\'t told to go to my events.',
		'VICTIM would be so easy to beat!',
		'VICTIM can\'t even defend his own microphone',
		'VICTIM did really poorly on television',
		'VICTIM could not stop Obama (twice)',
		'VICTIM out of self preservation, is concerned w/ my high poll #s',
		'VICTIM loses a fortune',
		'VICTIM doesn\'t have a clue',
		'VICTIM is trying to destroy Israel with all his bad moves',
		'VICTIM is living in a world of the make believe!',
		'VICTIM is the worst president in U.S. history!',
		'VICTIM looks and sounds so ridiculous',
		'VICTIM spends so much time speaking of the so-called Carbon footprint, and yet he flies all the way to Hawaii on a massive old 747',
		'VICTIM has a horrible attitude',
		'VICTIM is just so bad!',
		'VICTIM is hollowing out our military',
		'VICTIM is doing a terrible job',
		'VICTIM is doing many bad things behind our backs',
		'VICTIM is controlled by Mexican government?',
		'VICTIM has guests are stacked for Crooked Hillary!',
		'VICTIM is getting more and more biased',
		'VICTIM is so negative, getting even worse',
		'VICTIM is working hard to make me look as bad as possible',
		'VICTIM paid a fortune for an Iowa Poll, which shows me in first place over Cruz by 13%, 33% to 20% - then doesn\'t use it',
		'VICTIM is totally one-sided and biased against me that it is becoming boring',
		'VICTIM does not cover me accurately',
		'VICTIM has a major inferiority complex',
		'VICTIM is a dopey clown',
		'VICTIM has knowingly committed fraud',
		'VICTIM wants to control our U.S. politicians with daddy\'s money',
		'VICTIM is a really stupid talking head',
		'VICTIM is an embarrassed loser',
		'VICTIM lost all credibility',
		'VICTIM couldn\'t get elected dog catcher',
		'VICTIM forgot to mention my phenomenal biz success rate',
		'VICTIM didn\'t get the right gene.',
		'VICTIM reminds me of a spoiled brat without a properly functioning brain',
		'VICTIM is a third rate talent',
		'VICTIM is a total loser!',
		'VICTIM has no power in iowa',
		'VICTIM is so totally dishonest!',
		'VICTIM is unfair and biased',
		'VICTIM will always take a good story about me and make it bad',
		'VICTIM is a disgusting fraud',
		'VICTIM is laughing at the @nytimes for the lame hit piece they did on me and women',
		'VICTIM wrote yet another hit piece on me',
		'VICTIM is always trying to belittle',
		'VICTIM has lost its way!',
		'VICTIM never even calls to fact check',
		'VICTIM knowingly writes lies',
		'VICTIM allows dishonest writers to totally fabricate stories',
		'VICTIM should focus on fair and balanced reporting',
		'VICTIM made all bad decisions over the last decade',
		'VICTIM is falling apart',
		'VICTIM is always looking for a hit to bring them back into relevancy2014ain\'t working',
		'VICTIM is now irrelevant',
		'VICTIM is one of the dumbest people in politics',
		'VICTIM has no talent, no TV persona',
		'VICTIM is one of the least talented people on television',
		'VICTIM is a totally biased loser who doesn\'t have a clue',
		'VICTIM will be gone soon',
		'VICTIM is really hard to watch, has zero talent',
		'VICTIM, you have no idea what my strategy on ISIS is',
		'VICTIM is so average in so many ways!',
		'VICTIM is always complaining about Trump',
		'VICTIM is so average in every way',
		'VICTIM is very bad at math',
		'VICTIM should take another eleven day \'unscheduled\' vacation',
		'VICTIM is not very good or professional',
		'VICTIM really bombed tonight',
		'VICTIM is getting ready to treat me unfairly',
		'VICTIM is a total low life',
		'VICTIM will fade fast',
		'VICTIM is a major sleaze and buffoon',
		'VICTIM got thrown off of TV by NBC',
		'VICTIM has done nothing',
		'VICTIM is incapable of doing anything.',
		'VICTIM has failed miserably',
		'VICTIM is doing a lousy job in taking care of our Vets',
		'VICTIM let us down',
		'VICTIM graduated last in their class',
		'VICTIM should be defeated in the primaries',
		'VICTIM has gone really hostile ever since I said I won\'t do or watch the show anymore',
		'VICTIM doesn\'t have much power or insight!',
		'VICTIM has gone wild with hate',
		'VICTIM has the absolutely worst anti-Trump talking heads on his show',
		'VICTIM is a hater & racist',
		'VICTIM has to stop working to be so politically correct',
		'VICTIM asked if he could have pictures taken with me. I said fine. He then trashes on air!',
		'VICTIM is highly neurotic',
		'VICTIM was the WORST abuser of woman in U.S. political history',
		'VICTIM a gigantic hypocrite',
		'VICTIM was called a racist',
		'VICTIM dEMONSTRATED A PENCHANT FOR SEXISM',
		'VICTIM is so inappropriate',
		'VICTIM won\'t survive',
		'VICTIM has lost all credibility',
		'VICTIM endorsed a candidate who can\'t win',
		'VICTIM is desperate',
		'VICTIM begged me for ads',
		'VICTIM has been run into the ground',
		'VICTIM will be dead in 2 years',
		'VICTIM is so biased it is disgusting',
		'VICTIM treats me so badly',
		'VICTIM is incapable of understanding foreign policy',
		'VICTIM should know that the pyramids built for grain storage - don\'t people get it?',
		'VICTIM has never created a job in his life',
		'VICTIM isn\'t smart enough to know what\'s going on at the border',
		'VICTIM is not looking tough!',
		'VICTIM is not looking smart',
		'VICTIM is not looking good',
		'VICTIM totally lost control of illegal immigration, even with criminals',
		'VICTIM looks more and more like a paper tiger',
		'VICTIM is letting criminals knowingly stay in our country',
		'VICTIM is just a 3rd rate \'gotcha\' guy!',
		'VICTIM is kooky',
		'VICTIM is totally ineffective',
		'VICTIM is a low-level degenerate',
		'VICTIM should drop out of the race-stop wasting time & money',
		'VICTIM really went wacko today',
		'VICTIM can\'t function under pressure',
		'VICTIM is not very presidential',
		'VICTIM has NO path to victory',
		'VICTIM can never beat Hilary Clinton',
		'VICTIM is mathematically dead and totally desperate',
		'VICTIM hates New York',
		'VICTIM can\'t win with the voters so he has to sell himself to the bosses',
		'VICTIM can\'t get votes (I am millions ahead of him)',
		'VICTIM has to get his delegates from the Republican bosses',
		'VICTIM attacked New Yorkers and New York values- we don\'t forget!',
		'VICTIM has accomplished absolutely nothing',
		'VICTIM does not have the right \'temperment\' to be President',
		'VICTIM is the biggest liar in politics!',
		'VICTIM is acomplete & total liar',
		'VICTIM holds the Bible high and then lies and misrepresents the facts!',
		'VICTIM lies so much and is so dishonest',
		'VICTIM should be immediately disqualified in Iowa',
		'VICTIM told thousands of caucusgoers (voters) that Trump was strongly in favor of ObamaCare and \'choice\' - a total lie!',
		'VICTIM sent out a VOTER VIOLATION certificate to thousands of voters',
		'VICTIM didn\'t win Iowa, he illegally stole it',
		'VICTIM can\'t even get a Senator like @BenSasse, who is easy, to endorse him',
		'VICTIM will do anything to stay at the trough',
		'VICTIM is dropping like a rock',
		'VICTIM is in bed w/ Wall St.',
		'VICTIM is spending $millions on ads paid for by his N.Y. bosses',
		'VICTIM says one thing for money, does another for votes',
		'VICTIM is the ultimate hypocrite',
		'VICTIM did not list on his personal disclosure form personally guaranteed loans from banks. They own him!',
		'VICTIM is not much of a reformer',
		'VICTIM would speak behind my back, get caught, and then deny it',
		'VICTIM should not make statements behind closed doors to his bosses',
		'VICTIM made many bad calls',
		'VICTIM is one of the most overrated political pundits',
		'VICTIM is wrong almost all of the time',
		'VICTIM should be thrown off Fox News',
		'VICTIM is boring and totally biased',
		'VICTIM is a major lightweight with no credibility',
		'VICTIM has no honor!',
		'VICTIM was ran out of the race like a little boy',
		'VICTIM should respect me',
		'VICTIM is a dumb mouthpiece',
		'VICTIM got zero against me- no cred!',
		'VICTIM had zero in his presidential run before dropping out in disgrace',
		'VICTIM embarrasses himself with endorsement of Bush',
		'VICTIM embarrassed himself with his failed run for President',
		'VICTIM is so easy to beat!',
		'VICTIM is low energy',
		'VICTIM wants to look cool, but it\'s far too late',
		'VICTIM has no clue',
		'VICTIM is spending a fortune of special interest against me in SC',
		'VICTIM is desperate and SAD!',
		'VICTIM gave up and enlisted Mommy and his brother',
		'VICTIM is by far the weakest of the lot',
		'VICTIM has gone nasty with lies',
		'VICTIM is a pathetic figure!',
		'VICTIM spent a fortune of special interest money on a Super Bowl ad',
		'VICTIM has zero communication skills',
		'VICTIM had to bring in mommy to take a slap at me',
		'VICTIM should go home and relax!',
		'VICTIM is a total embarrassment to himself and his family',
		'VICTIM is a basket case',
		'VICTIM has been confused for forty years',
		'VICTIM is bad on women\'s health issues',
		'VICTIM is miserable',
		'VICTIM just doesn\'t get it',
		'VICTIM will never secure the border',
		'VICTIM will NEVER Make America Great Again',
		'VICTIM has gone off the deep end',
		'VICTIM misrepresents my positions!',
		'VICTIM is rapidly fading',
		'VICTIM is so off the rails',
		'VICTIM is a waste of time',
		'VICTIM just doesn\'t know about winning',
		'VICTIM is now in total freefall',
		'VICTIM is one of the dumber bloggers',
		'VICTIM is really boring, slow, lethargic',
		'VICTIM wouldn\'t know the truth if it hit him in the face',
		'VICTIM has paid ZERO respect to the great police and law enforcement professionals',
		'VICTIM is a sleazebag',
		'VICTIM is not only breaking the spirit of the law but the law itself',
		'VICTIM is spending more time doing a forensic analysis of Melania\'s speech than the FBI spent on Hillary\'s emails',
		'VICTIM is trying their absolute best to depict a star in a tweet as the Star of David rather than a Sheriff\'s Star, or plain star!',
		'VICTIM is so totally biased',
		'VICTIM is on a new phony kick about my management style',
		'VICTIM has not covered my long-shot great finish in Iowa fairly',
		'VICTIM will not report the highly respected new national poll that just came out',
		'VICTIM is rambling and overly flamboyant',
		'VICTIM begged my people for a job',
		'VICTIM is virtually incompetent',
		'VICTIM allowed Crooked Hillary to get away with \'murder\'',
		'VICTIM is totally rigged and corrupt!',
		'VICTIM bombed last night!',
		'VICTIM is very racist!',
		'VICTIM has a nasty mouth',
		'VICTIM is one of the least productive U.S. Senators',
		'VICTIM gets nothing done',
		'VICTIM does nothing to help!',
		'VICTIM didn\'t have the guts to run for POTUS',
		'VICTIM has a career that is totally based on a lie',
		'VICTIM wrote letter to me begging for forgiveness',
		'VICTIM selfishly opposed to me!',
		'VICTIM should resign',
		'VICTIM is totally biased against me',
		'VICTIM was going off the air until I came along',
		'VICTIM knows so little about politics',
		'VICTIM will be fired like a dog',
		'VICTIM doesn\'t have a natural instinct for politics',
		'VICTIM registers ZERO in the polls',
		'VICTIM couldn\'t be elected dog catcher if he ran again',
		'VICTIM spent $1,000 to register in New Hampshire & dropped out the next day. Such a waste!',
		'VICTIM registered at less than 1 percent in the polls',
		'VICTIM is such a mess',
		'VICTIM knows nothing about me',
		'VICTIM did a terrible job against me',
		'VICTIM will lead to at least partial world destruction',
		'VICTIM is a catastrophe',
		'VICTIM made one of the dumbest & most dangerous misjudgments ever',
		'VICTIM poses a direct national security threat',
		'VICTIM wants $120,000 to make a boring speech',
		'VICTIM covers me very inaccurately',
		'VICTIM did a 1 hour hit job on me today',
		'VICTIM is totally out of control',
		'VICTIM treats me very badly',
		'VICTIM is trying hard to disguise their massive Muslim problem',
		'VICTIM will drop like a rock in the polls',
		'VICTIM is good for Mexico!',
		'VICTIM doesn\'t have what it takes',
		'VICTIM can\'t debate',
		'VICTIM fell right into President Obama\'s trap on ObamaCare',
		'VICTIM came in dead last',
		'VICTIM is so irrelevant to the race',
		'VICTIM is uncomfortable looking',
		'VICTIM sucks and is are bad for U.S.A.',
		'VICTIM wants to continue our bad trade deals',
		'VICTIM wasted a lot of time and money',
		'VICTIM is weak and totally conflicted',
		'VICTIM is dumb as a rock',
		'VICTIM did a terrible job of ticket distrbution',
		'VICTIM won\'t even call it what it is - RADICAL ISLAM!',
		'VICTIM has zero credibility',
		'VICTIM is very dumb and failing',
		'VICTIM is a mental basketcase',
		'VICTIM always seems to be crying'
	},
	slaps = {
		'VICTIM was shot by VICTOR.',
		'VICTIM was pricked to death.',
		'VICTIM walked into a cactus while trying to escape VICTOR.',
		'VICTIM drowned.',
		'VICTIM drowned whilst trying to escape VICTOR.',
		'VICTIM blew up.',
		'VICTIM was blown up by VICTOR.',
		'VICTIM hit the ground too hard.',
		'VICTIM fell from a high place.',
		'VICTIM fell off a ladder.',
		'VICTIM fell into a patch of cacti.',
		'VICTIM was doomed to fall by VICTOR.',
		'VICTIM was blown from a high place by VICTOR.',
		'VICTIM was squashed by a falling anvil.',
		'VICTIM went up in flames.',
		'VICTIM burned to death.',
		'VICTIM was burnt to a crisp whilst fighting VICTOR.',
		'VICTIM walked into a fire whilst fighting VICTOR.',
		'VICTIM tried to swim in lava.',
		'VICTIM tried to swim in lava while trying to escape VICTOR.',
		'VICTIM was struck by lightning.',
		'VICTIM was slain by VICTOR.',
		'VICTIM got finished off by VICTOR.',
		'VICTIM was killed by magic.',
		'VICTIM was killed by VICTOR using magic.',
		'VICTIM starved to death.',
		'VICTIM suffocated in a wall.',
		'VICTIM fell out of the world.',
		'VICTIM was knocked into the void by VICTOR.',
		'VICTIM withered away.',
		'VICTIM was pummeled by VICTOR.',
		'VICTIM was fragged by VICTOR.',
		'VICTIM was desynchronized.',
		'VICTIM was wasted.',
		'VICTIM was busted.',
		'VICTIM\'s bones are scraped clean by the desolate wind.',
		'VICTIM has died of dysentery.',
		'VICTIM fainted.',
		'VICTIM is out of usable Pokemon! VICTIM whited out!',
		'VICTIM is out of usable Pokemon! VICTIM blacked out!',
		'VICTIM whited out!',
		'VICTIM blacked out!',
		'VICTIM says goodbye to this cruel world.',
		'VICTIM got rekt.',
		'VICTIM was sawn in half by VICTOR.',
		'VICTIM died. I blame VICTOR.',
		'VICTIM was axe-murdered by VICTOR.',
		'VICTIM\'s melon was split by VICTOR.',
		'VICTIM was sliced and diced by VICTOR.',
		'VICTIM was split from crotch to sternum by VICTOR.',
		'VICTIM\'s death put another notch in VICTOR\'s axe.',
		'VICTIM died impossibly!',
		'VICTIM died from VICTOR\'s mysterious tropical disease.',
		'VICTIM escaped infection by dying.',
		'VICTIM played hot-potato with a grenade.',
		'VICTIM was knifed by VICTOR.',
		'VICTIM fell on his sword.',
		'VICTIM ate a grenade.',
		'VICTIM practiced being VICTOR\'s clay pigeon.',
		'VICTIM is what\'s for dinner!',
		'VICTIM was terminated by VICTOR.',
		'VICTIM was shot before being thrown out of a plane.',
		'VICTIM was not invincible.',
		'VICTIM has encountered an error.',
		'VICTIM died and reincarnated as a goat.',
		'VICTOR threw VICTIM off a building.',
		'VICTIM is sleeping with the fishes.',
		'VICTIM got a premature burial.',
		'VICTOR replaced all of VICTIM\'s music with Nickelback.',
		'VICTOR spammed VICTIM\'s email.',
		'VICTOR made VICTIM a knuckle sandwich.',
		'VICTOR slapped VICTIM with pure nothing.',
		'VICTOR hit VICTIM with a small, interstellar spaceship.',
		'VICTIM was quickscoped by VICTOR.',
		'VICTOR put VICTIM in check-mate.',
		'VICTOR RSA-encrypted VICTIM and deleted the private key.',
		'VICTOR put VICTIM in the friendzone.',
		'VICTOR slaps VICTIM with a DMCA takedown request!',
		'VICTIM became a corpse blanket for VICTOR.',
		'Death is when the monsters get you. Death comes for VICTIM.',
		'Cowards die many times before their death. VICTIM never tasted death but once.',
		'VICTIM died of hospital gangrene.',
		'VICTIM got a house call from Doctor VICTOR.',
		'VICTOR beheaded VICTIM.',
		'VICTIM got stoned...by an angry mob.',
		'VICTOR sued the pants off VICTIM.',
		'VICTIM was impeached.',
		'VICTIM was one-hit KO\'d by VICTOR.',
		'VICTOR sent VICTIM to /dev/null.',
		'VICTOR sent VICTIM down the memory hole.',
		'VICTIM was a mistake.',
		'\'VICTIM was a mistake.\' - VICTOR',
		'VICTOR checkmated VICTIM in two moves.'
	},
	puns = {
		'The person who invented the door-knock won the No-bell prize.',
		'I couldn\'t work out how to fasten my seatbelt. Then it clicked.',
		'Never trust atoms; they make up everything.',
		'Singing in the shower is all fun and games until you get shampoo in your mouth - Then it becomes a soap opera.',
		'I can\'t believe I got fired from the calendar factory. All I did was take a day off.',
		'To the guy who invented zero: Thanks for nothing!',
		'Enough with the cripple jokes! I just can\'t stand them.',
		'I\'ve accidentally swallowed some Scrabble tiles. My next crap could spell disaster.',
		'How does Moses make his tea? Hebrews it.',
		'Did you hear about the guy who got hit in the head with a can of soda? He was lucky it was a soft drink.',
		'When William joined the army he disliked the phrase \'fire at will\'.',
		'There was a sign on the lawn at a rehab center that said \'Keep off the Grass\'.',
		'I wondered why the baseball was getting bigger. Then it hit me.',
		'I can hear music coming out of my printer. I think the paper\'s jamming again.',
		'I have a few jokes about unemployed people, but none of them work',
		'Want to hear a construction joke? I\'m working on it',
		'I always take a second pair of pants when I go golfing, in case I get a hole in one.',
		'I couldn\'t remember how to catch a boomerang, but then it came back to me.',
		'I\'ve decided that my Wi-Fi router will be my valentine this year. I don\'t know why, we just have this connection.',
		'A prisoner\'s favourite punctuation mark is the period. It marks the end of his sentence.',
		'I used to go fishing with Skrillex, but he kept dropping the bass.',
		'Two antennae met on a roof and got married. The wedding was okay, but the reception was incredible.',
		'A book just fell on my head. I\'ve only got my shelf to blame.',
		'I dropped my steak on the floor. Now it\'s ground beef.',
		'I used to have a fear of hurdles, but I got over it.',
		'The outcome of war does not prove who is right, but only who is left.',
		'Darth Vader tries not to burn his food, but it always comes out a little on the dark side.',
		'The store keeps calling me to buy more furniture, but all I wanted was a one night stand.',
		'This girl said she recognized me from the vegetarian club, but I\'d never met herbivore.',
		'Police arrested two kids yesterday, one was drinking battery acid, the other was eating fireworks. They charged one and let the other one off...',
		'No more Harry Potter jokes guys. I\'m Sirius.',
		'It was hard getting over my addiction to hokey pokey, but I\'ve turned myself around.',
		'It takes a lot of balls to golf the way I do.',
		'Why did everyone want to hang out with the mushroom? Because he was a fungi.',
		'How much does a hipster weigh? An instagram.',
		'I used to be addicted to soap, but I\'m clean now.',
		'When life gives you melons, you\'re probably dyslexic.',
		'What\'s with all the blind jokes? I just don\'t see the point.',
		'If Apple made a car, would it have Windows?',
		'Need an ark? I Noah guy.',
		'The scarecrow won an award because he was outstanding in his field.',
		'What\'s the difference between a man in a tux on a bicycle, and a man in a sweatsuit on a trycicle? A tire.',
		'What do you do with a sick chemist? If you can\'t helium, and you can\'t curium, you\'ll just have to barium.',
		'I\'m reading a book about anti-gravity. It\'s impossible to put down.',
		'Trying to write with a broken pencil is pointless.',
		'When TVs go on vacation, they travel to remote islands.',
		'I was going to tell a midget joke, but it\'s too short.',
		'Jokes about German sausages are the wurst.',
		'How do you organize a space party? You planet.',
		'Sleeping comes so naturally to me, I could do it with my eyes closed.',
		'I\'m glad I learned sign language; it\'s pretty handy.',
		'Atheism is a non-prophet organization.',
		'Velcro: What a rip-off!',
		'If they made a Minecraft movie, it would be a blockbuster.',
		'I don\'t trust people with graph paper. They\'re always plotting something',
		'I had a friend who was addicted to brake fluid. He says he can stop anytime.',
		'The form said I had Type A blood, but it was a Type O.',
		'I went to to the shop to buy eight Sprites -  I came home and realised I\'d picked 7-Up.',
		'There was an explosion at a pie factory. 3.14 people died.',
		'A man drove his car into a tree and found out how a Mercedes bends.',
		'The experienced carpenter really nailed it, but the new guy screwed everything up.',
		'I didn\'t like my beard at first, but then it grew on me.',
		'Smaller babies may be delivered by stork, but the heavier ones need a crane.',
		'What\'s the definition of a will? It\'s a dead giveaway.',
		'I was going to look for my missing watch, but I could never find the time.',
		'I hate elevators, and I often take steps to avoid them.',
		'Did you hear about the guy whose whole left side was cut off? He\'s all right now.',
		'It\'s not that the man did not know how to juggle, he just didn\'t have the balls to do it.',
		'I used to be a loan shark, but I lost interest',
		'I don\'t trust these stairs; they\'re always up to something.',
		'My friend\'s bakery burned down last night. Now his business is toast.',
		'Don\'t trust people that perform acupuncture; they\'re back stabbers.',
		'The man who survived mustard gas and pepper spray is now a seasoned veteran.',
		'Police were called to a daycare where a three-year-old was resisting a rest.',
		'When Peter Pan punches, they Neverland',
		'The shoemaker did not deny his apprentice anything he needed. He gave him his awl.',
		'I did a theatrical performance about puns. It was a play on words.',
		'Show me a piano falling down a mineshaft and I\'ll show you A-flat minor.',
		'Have you ever tried to eat a clock? It\'s very time consuming.',
		'There was once a cross-eyed teacher who couldn\'t control his pupils.',
		'A new type of broom came out and it is sweeping the nation.',
		'I relish the fact that you\'ve mustard the strength to ketchup to me.',
		'I knew a woman who owned a taser. Man, was she stunning!',
		'What did the grape say when it got stepped on? Nothing - but it let out a little whine.',
		'It was an emotional wedding. Even the cake was in tiers.',
		'When a clock is hungry it goes back four seconds.',
		'The dead batteries were given out free of charge.',
		'Why are there no knock-knock jokes about America? Because freedom rings.',
		'When the cannibal showed up late to dinner, they gave him the cold shoulder.',
		'I should have been sad when my flashlight died, but I was delighted.',
		'Why don\'t tennis players ever get married? Love means nothing to them.',
		'Pterodactyls can\'t be heard going to the bathroom because the P is silent.',
		'Mermaids make calls on their shell phones.',
		'What do you call an aardvark with three feet? A yaardvark.',
		'Captain Kirk has three ears: A right ear, a left ear, and a final front ear.',
		'How do celebrities stay cool? They have a lot of fans.',
		'Without geometry, life is pointless.',
		'Did you hear about the cow who tried to jump over a barbed-wire fence? It ended in udder destruction.',
		'The truth may ring like a bell, but it is seldom ever tolled.',
		'I used to work for the IRS, but my job was too taxing.',
		'I used to be a programmer, but then I lost my drive.',
		'Pediatricians are doctors with little patients.',
		'I finally fired my masseuse today. She always rubbed me the wrong way.',
		'I stayed up all night wondering where the sun went. Then it dawned on me.',
		'What\'s the difference between a man and his dog? The man wears a suit; the dog just pants.',
		'A psychic midget who escapes from prison is a small medium at large.',
		'I\'ve been to the dentist several times, so I know the drill.',
		'The roundest knight at King Arthur\'s round table was Sir Cumference. He acquired his size from too much pi.',
		'She was only a whiskey maker, but he loved her still.',
		'Male deer have buck teeth.',
		'Whiteboards are remarkable.',
		'Visitors in Cuba are always Havana good time.',
		'Why does electricity shock people? It doesn\'t know how to conduct itself.',
		'Lancelot had a scary dream about his horse. It was a knight mare.',
		'A tribe of cannibals captured a missionary and ate him. Afterwards, they all had violent food poisoning. This just goes to show that you can\'t keep a good man down.',
		'Heaven for gamblers is a paradise.',
		'Old wheels aren\'t thrown away, they\'re just retired.',
		'Horses are very stable animals.',
		'Bankers don\'t crash, they just lose their balance.',
		'The career of a skier can go downhill very fast.',
		'In democracy, it\'s your vote that counts. In feudalism, it\'s your count that votes.',
		'A sea lion is nothing but an ionized seal.',
		'The vegetables from my garden aren\'t that great. I guess you could say they\'re mediokra.'
	},
	commits = {
		'One does not simply merge into master',
		'Merging the merge',
		'Another bug bites the dust',
		'de-misunderestimating',
		'Some shit.',
		'add actual words',
		'I CAN HAZ COMMENTZ.',
		'giggle.',
		'Whatever.',
		'Finished fondling.',
		'FONDLED THE CODE',
		'this is how we generate our shit.',
		'unh',
		'It works!',
		'unionfind is no longer being molested.',
		'Well, it\'s doing something.',
		'I\'M PUSHING.',
		'Whee.',
		'Whee, good night.',
		'It\'d be nice if type errors caused the compiler to issue a type error',
		'Fucking templates.',
		'I hate this fucking language.',
		'marks',
		'that coulda been bad',
		'hoo boy',
		'It was the best of times, it was the worst of times',
		'Fucking egotistical bastard. adds expandtab to vimrc',
		'if you\'re not using et, fuck off',
		'WHO THE FUCK CAME UP WITH MAKE?',
		'This is a basic implementation that works.',
		'By works, I meant \'doesn\'t work\'. Works now..',
		'Last time I said it works? I was kidding. Try this.',
		'Just stop reading these for a while, ok..',
		'Give me a break, it\'s 2am. But it works now.',
		'Make that it works in 90% of the cases. 3:30.',
		'Ok, 5am, it works.  For real.',
		'FOR REAL.',
		'I don\'t know what these changes are supposed to accomplish but somebody told me to make them.',
		'I don\'t get paid enough for this shit.',
		'fix some fucking errors',
		'first blush',
		'So my boss wanted this button ...',
		'uhhhhhh',
		'forgot we\'re not using a smart language',
		'include shit',
		'To those I leave behind, good luck!',
		'things occurred',
		'i dunno, maybe this works',
		'8==========D',
		'No changes made',
		'whooooooooooooooooooooooooooo',
		'clarify further the brokenness of C++. why the fuck are we using C++?',
		'.',
		'Friday 5pm',
		'changes',
		'A fix I believe, not like I tested or anything',
		'Useful text',
		'pgsql is being a pain',
		'pgsql is more strict, increase the hackiness up to 11',
		'c&p fail',
		'syntax',
		'fix',
		'just shoot me',
		'arrrggghhhhh fixed!',
		'someone fails and it isn\'t me',
		'totally more readable',
		'better grepping',
		'fix',
		'fix bug, for realz',
		'fix /sigh',
		'Does this work',
		'MOAR BIFURCATION',
		'bifurcation',
		'REALLY FUCKING FIXED',
		'FIX',
		'better ignores',
		'More ignore',
		'more ignores',
		'more ignores',
		'more ignores',
		'more ignores',
		'more ignores',
		'more ignored words',
		'more fixes',
		'really ignore ignored worsd',
		'fixes',
		'/sigh',
		'fix',
		'fail',
		'pointless limitation',
		'omg what have I done?',
		'added super-widget 2.0.',
		'tagging release w.t.f.',
		'I can\'t believe it took so long to fix this.',
		'I must have been drunk.',
		'This is why the cat shouldn\'t sit on my keyboard.',
		'This is why git rebase is a horrible horrible thing.',
		'ajax-loader hotness, oh yeah',
		'small is a real HTML tag, who knew.',
		'WTF is this.',
		'Do things better, faster, stronger',
		'Use a real JS construct, WTF knows why this works in chromium.',
		'Added a banner to the default admin page. Please have mercy on me =(',
		'needs more cow bell',
		'Switched off unit test X because the build had to go out now and there was no time to fix it properly.',
		'Updated',
		'I must sleep... it\'s working... in just three hours...',
		'I was wrong...',
		'Completed with no bugs...',
		'Fixed a little bug...',
		'Fixed a bug in NoteLineCount... not seriously...',
		'woa!! this one was really HARD!',
		'Made it to compile...',
		'changed things...',
		'touched...',
		'i think i fixed a bug...',
		'perfect...',
		'Moved something to somewhere... goodnight...',
		'oops, forgot to add the file',
		'Corrected mistakes',
		'oops',
		'oops!',
		'put code that worked where the code that didn\'t used to be',
		'Nothing to see here, move along',
		'I am even stupider than I thought',
		'I don\'t know what the hell I was thinking.',
		'fixed errors in the previous commit',
		'Committed some changes',
		'Some bugs fixed',
		'Minor updates',
		'Added missing file in previous commit',
		'bug fix',
		'typo',
		'bara bra grejjor',
		'Continued development...',
		'Does anyone read this? I\'ll be at the coffee shop accross the street.',
		'That\'s just how I roll',
		'work in progress',
		'minor changes',
		'some brief changes',
		'assorted changes',
		'lots and lots of changes',
		'another big bag of changes',
		'lots of changes after a lot of time',
		'LOTS of changes. period',
		'Test commit. Please ignore',
		'I\'m just a grunt. Don\'t blame me for this awful PoS.',
		'I did it for the lulz!',
		'I\'ll explain this when I\'m sober .. or revert it',
		'Obligatory placeholder commit message',
		'A long time ago, in a galaxy far far away...',
		'Fixed the build.',
		'various changes',
		'One more time, but with feeling.',
		'Handled a particular error.',
		'Fixed unnecessary bug.',
		'Removed code.',
		'Added translation.',
		'Updated build targets.',
		'Refactored configuration.',
		'Locating the required gigapixels to render...',
		'Spinning up the hamster...',
		'Shovelling coal into the server...',
		'Programming the flux capacitor',
		'The last time I tried this the monkey didn\'t survive. Let\'s hope it works better this time.',
		'I should have had a V8 this morning.',
		'640K ought to be enough for anybody',
		'pay no attention to the man behind the curtain',
		'a few bits tried to escape, but we caught them',
		'Who has two thumbs and remembers the rudiments of his linear algebra courses?  Apparently, this guy.',
		'workaround for ant being a pile of fail',
		'Don\'t push this commit',
		'rats',
		'squash me',
		'fixed mistaken bug',
		'Final commit, ready for tagging',
		'-m \'So I hear you like commits ...\'',
		'epic',
		'need another beer',
		'Well the book was obviously wrong.',
		'lolwhat?',
		'Another commit to keep my CAN streak going.',
		'I cannot believe that it took this long to write a test for this.',
		'TDD: 1, Me: 0',
		'Yes, I was being sarcastic.',
		'Apparently works-for-me is a crappy excuse.',
		'tl;dr',
		'I would rather be playing SC2.',
		'Crap. Tonight is raid night and I am already late.',
		'I know what I am doing. Trust me.',
		'You should have trusted me.',
		'Is there an award for this?',
		'Is there an achievement for this?',
		'I\'m totally adding this to epic win. +300',
		'This really should not take 19 minutes to build.',
		'fixed the israeli-palestinian conflict',
		'SHIT ===> GOLD',
		'Committing in accordance with the prophecy.',
		'It compiles! Ship it!',
		'LOL!',
		'Reticulating splines...',
		'SEXY RUSSIAN CODES WAITING FOR YOU TO CALL',
		's/import/include/',
		'extra debug for stuff module',
		'debug line test',
		'debugo',
		'remove debug all good',
		'debug suff',
		'more debug... who overwrote!',
		'these confounded tests drive me nuts',
		'For great justice.',
		'QuickFix.',
		'oops - thought I got that one.',
		'removed echo and die statements, lolz.',
		'somebody keeps erasing my changes.',
		'doh.',
		'pam anderson is going to love me.',
		'added security.',
		'arrgghh... damn this thing for not working.',
		'jobs... steve jobs',
		'and a comma',
		'this is my quickfix branch and i will use to do my quickfixes',
		'Fix my stupidness',
		'and so the crazy refactoring process sees the sunlight after some months in the dark!',
		'gave up and used tables.',
		'[Insert your commit message here. Be sure to make it descriptive.]',
		'Removed test case since code didn\'t pass QA',
		'removed tests since i can\'t make them green',
		'stuff',
		'more stuff',
		'Become a programmer, they said. It\'ll be fun, they said.',
		'Same as last commit with changes',
		'foo',
		'just checking if git is working properly...',
		'fixed some minor stuff, might need some additional work.',
		'just trolling the repo',
		'All your codebase are belong to us.',
		'Somebody set up us the bomb.',
		'should work I guess...',
		'To be honest, I do not quite remember everything I changed here today. But it is all good, I tell ya.',
		'well crap.',
		'herpderp (redux)',
		'herpderp',
		'Derp',
		'derpherp',
		'Herping the derp',
		'sometimes you just herp the derp so hard it herpderps',
		'Derp. Fix missing constant post rename',
		'Herping the fucking derp right here and now.',
		'Derp, asset redirection in dev mode',
		'mergederp',
		'Derp search/replace fuckup',
		'Herpy dooves.',
		'Derpy hooves',
		'derp, helper method rename',
		'Herping the derp derp (silly scoping error)',
		'Herp derp I left the debug in there and forgot to reset errors.',
		'Reset error count between rows. herpderp',
		'hey, what\'s that over there?!',
		'hey, look over there!',
		'It worked for me...',
		'Does not work.',
		'Either Hot Shit or Total Bollocks',
		'Arrrrgggg',
		'Don’t mess with Voodoo',
		'I expected something different.',
		'Todo!!!',
		'This is supposed to crash',
		'No changes after this point.',
		'I know, I know, this is not how I\'m supposed to do it, but I can\'t think of something better.',
		'Don’t even try to refactor it.',
		'(c) Microsoft 1988',
		'Please no changes this time.',
		'Why The Fuck?',
		'We should delete this crap before shipping.',
		'Shit code!',
		'ALL SORTS OF THINGS',
		'Herpderp, shoulda check if it does really compile.',
		'I CAN HAZ PYTHON, I CAN HAZ INDENTS',
		'Major fixup.',
		'less french words',
		'breathe, =, breathe',
		'IEize',
		'this doesn\'t really make things faster, but I tried',
		'this should fix it',
		'forgot to save that file',
		'Glue. Match sticks. Paper. Build script!',
		'Argh! About to give up :(',
		'Blaming regex.',
		'oops',
		'it\'s friday',
		'yo recipes',
		'Not sure why',
		'lol digg',
		'grrrr',
		'For real, this time.',
		'Feed. You. Stuff. No time.',
		'I don\'t give a damn \'bout my reputation',
		'DEAL WITH IT',
		'commit',
		'tunning',
		'I really should\'ve committed this when I finished it...',
		'it\'s getting hard to keep up with the crap I\'ve trashed',
		'I honestly wish I could remember what was going on here...',
		'I must enjoy torturing myself',
		'For the sake of my sanity, just ignore this...',
		'That last commit message about silly mistakes pales in comparision to this one',
		'My bad',
		'Still can\'t get this right...',
		'Nitpicking about alphabetizing methods, minor OCD thing',
		'Committing fixes in the dark, seriously, who killed my power!?',
		'You can\'t see it, but I\'m making a very angry face right now',
		'Fix the fixes',
		'it\'s secret!',
		'Commit committed....',
		'No time to commit.. My people need me!',
		'Something fixed',
		'I\'m hungry',
		'asdfasdfasdfasdfasdfasdfadsf',
		'hmmm',
		'formatted all',
		'Replace all whitespaces with tabs.',
		's/ /  /g',
		'I\'m too foo for this bar',
		'Things went wrong...',
		'??! what the ...',
		'This solves it.',
		'Working on tests (haha)',
		'fixed conflicts (LOL merge -s ours; push -f)',
		'last minute fixes.',
		'fuckup.',
		'Revert \'fuckup\'.',
		'should work now.',
		'final commit.',
		'done. going to bed now.',
		'buenas those-things.',
		'Your commit is writing cheques your merge can\'t cash.',
		'This branch is so dirty, even your mom can\'t clean it.',
		'wip',
		'Revert \'just testing, remember to revert\'',
		'bla',
		'harharhar',
		'restored deleted entities just to be sure',
		'added some filthy stuff',
		'bugger',
		'lol',
		'oopsie B|',
		'Copy pasta fail. still had a instead of a',
		'Now added delete for real',
		'grmbl',
		'move your body every every body',
		'Trying to fake a conflict',
		'And a commit that I don\'t know the reason of...',
		'ffs',
		'that\'s all folks',
		'Fucking submodule bull shit',
		'apparently i did something…',
		'bump to 0.0.3-dev:wq',
		'pep8 - cause I fell like doing a barrel roll',
		'pep8 fixer',
		'it is hump day _^_',
		'happy monday _ bleh _',
		'after of this commit remember do a git reset hard',
		'someday I gonna kill someone for this shit...',
		'magic, have no clue but it works',
		'I am sorry',
		'dirty hack, have a better idea ?',
		'Code was clean until manager requested to fuck it up',
		' - Temporary commit.',
		':(:(',
		'...',
		'GIT :/',
		'stopped caring 10 commits ago',
		'Testing in progress ;)',
		'Fixed Bug',
		'Fixed errors',
		'Push poorly written test can down the road another ten years',
		'commented out failing tests',
		'I\'m human',
		'TODO: write meaningful commit message',
		'Pig',
		'SOAP is a piece of shit',
		'did everything',
		'project lead is allergic to changes...',
		'making this thing actually usable.',
		'I was told to leave it alone, but I have this thing called OCD, you see',
		'Whatever will be, will be 8{',
		'it\'s 2016; why are we using ColdFusion?!',
		'#GrammarNazi',
		'Future self, please forgive me and don\'t hit me with the baseball bat again!',
		'Hide those navs, boi!',
		'Who knows...',
		'Who knows WTF?!',
		'I should get a raise for this.',
		'Done, to whoever merges this, good luck.',
		'Not one conflict, today was a good day.',
		'First Blood',
		'Fixed the fuck out of #526!',
		'I\'m too old for this shit!',
		'One little whitespace gets its very own commit! Oh, life is so erratic!',
		'please dont let this be the problem',
		'good: no crash. bad: nothing happens',
		'trying',
		'trying harder',
		'i tried',
		'fml'
	}
} -- End of configuration, you're good to go!
